django_movie/django_movie/apps/contact/urls.py
from django.urls import path

from .views import ContactView

app_name='contact'
urlpatterns = [
    path('', ContactView.as_view(), name='contact'),
]

django_movie/django_movie/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]
urlpatterns += i18n_patterns(
    path('accounts/', include('allauth.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('contact/', include('contact.urls')),
    path('', include('movies.urls')),
)

'''Добавляет фото в /media/'''
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_movie/django_movie/apps/contact/models.py
from django.db import models

class Contact(models.Model):
    """Подписка по email"""
    email = models.EmailField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = "Контакт"
        verbose_name_plural = "Контакты"

django_movie/django_movie/apps/contact/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    """Форма подписи по email"""
    class Meta:
        model = Contact
        fields = ("email", )
        widgets = {
            "email": forms.TextInput(attrs={"class": "editContent", "placeholder": "Введите ваш Email..."})
        }
        labels = {
            "email": ""
        }

django_movie/django_movie/apps/contact/views.py
from django.shortcuts import render
from .models import Contact
from .forms import ContactForm
from django.views.generic import CreateView

class ContactView(CreateView):
    model = Contact
    form_class = ContactForm
    success_url = "/"

django_movie/templates/contact/tags/form.html
<h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3" >
    Рассылка новинок кино
</h3>

    <p class="editContent">
        Подписавшись на нашу email рассылку вы всегда будете в курсе новинок кино на сайте.
    </p>

    <form action="{% url 'contact:contact' %}" method="post" class="w3layouts-newsletter">
        {% csrf_token %}
        {{ contact_form }}
        <button class="btn1 btn" ><span class="fa fa-paper-plane-o" aria-hidden="true" ></span></button>

    </form>